### ISSUE TITLE
ifType

### ISSUE THREAD

**Issue by andrewjmead** [dresende/node-enforce#2]
I'm using this because it's the provided validator for node-orm2.

I'm trying to validate if an attribute is a `boolean`.

I tried 

```
validations: {
    setting_ticket_email_alerts: orm.enforce.notEmptyString().ifType('boolean')
}
```

and

```
validations: {
    setting_ticket_email_alerts: orm.enforce.ifType('boolean')
}
```

Neither of these chunks work correctly.

I saw that custom validations are supported, but could not find any examples or the api. Could you provide a link?

**Comment by elad** [comment]
@andrewjmead - do you mean that you ended up **not** using `ifType`?

**Comment by andrewjmead** [comment]
@elad I'll have to be honest, I forget everything about this issue.

**Comment by elad** [comment]
@andrewjmead do you still use node-enforce for validation...? :)

**Comment by andrewjmead** [comment]
@elad I do not, sorry.

**Comment by elad** [comment]
@andrewjmead it's all good - I tried using it for the same reason you stated above (it's used by node-orm2) but I very quickly decided against it. Thanks for your prompt replies!

**Comment by andrewjmead** [comment]
@elad FYI, I moved to waterline for my ORM.

**Comment by elad** [comment]
@andrewjmead thanks for the pointer! I will definitely be looking into it. :)
